### ISSUE TITLE
problem importing flavio

### ISSUE THREAD

**Issue by zaineb1190** [flav-io/flavio#97] opened 2019-11-20 06:58 UTC
Hi, I have problem importing flavio. I get these errors. How to fix it?

Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flavio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/protyush18/.local/lib/python3.6/site-packages/flavio/__init__.py", line 2, in <module>
    from . import physics
  File "/home/protyush18/.local/lib/python3.6/site-packages/flavio/physics/__init__.py", line 15, in <module>
    from . import eft
  File "/home/protyush18/.local/lib/python3.6/site-packages/flavio/physics/eft.py", line 3, in <module>
    import wcxf
ModuleNotFoundError: No module named 'wcxf'
>>>

**Comment by DavidMStraub** [comment] 2019-11-20 07:02
Duplicate of #95.

We will release a new version in a few hours.

**Closed by DavidMStraub** 2019-11-20 07:02 UTC

**Comment by peterstangl** [comment] 2019-11-20 14:20
@zaineb1190 now that the new flavio version is released, just upgrade as described in https://flav-io.github.io/docs/installation.html and your problem should be solved.
